package entity;

public interface MessageType {
	String LOGIN = "LOGIN";
	String LOGIN_SUCCESS = "LOGIN_SUCCESS";
	String LOGIN_FAILURE = "LOGIN_FAILURE";
	
	String REGISTER = "REGISTER";
	String REGISTER_SUCCESS = "REGISTER_SUCCESS";
	String REGISTER_FAILURE = "REGISTER_FAILURE";
	
	String NEWCONTACT = "NEWCONTACT";
	String NEWCONTACT_SUCCESS = "NEWCONTACT_SUCCESS";
	String NEWCONTACT_FAILURE = "NEWCONTACT_FAILURE";
	
	String DELETECONTACT = "DELETECONTACT";
	String DELETECONTACT_SUCCESS = "DELETECONTACT_SUCCESS";
	String DELETECONTACT_FAILURE = "DELETECONTACT_FAILURE";
	
	String READCONTACT = "READCONTACT";
	String READCONTACT_SUCCESS = "READCONTACT_SUCCESS";
	String READCONTACT_RAILURE = "READCONTACT_FAILURE";
	
	String READDANGER = "READDANGER";
	String READDANGER_SUCCESS = "READDANGER_SUCCESS";
	String READDANGER_FAILURE = "READDANGER_FAILURE";
	
	String STARTLISTEN = "STARTLISTEN";
	String STARTLISTEN_SUCCESS = "STARTLISTEN_SUCCESS";
	String STARTLISTEN_FAILURE = "STARTLISTEN_FAILURE";
	
	String STOPLISTEN = "STOPLISTEN";
	String STOPLISTEN_SUCCESS = "STOPLISTEN_SUCCESS";
	String STOPLISTEN_FAILURE = "STOPLISTEN_FAILURE";
	
	String INDANGER = "INDANGER";
	String INSERT_SUCCESS = "INSERT_SUCCESS";
	String INSERT_FAILURE = "INSERT_FAILURE";
	
	String DELETEDANGER = "DELETEDANGER";
	String DELETEDANGER_SUCCESS = "DELETEDANGER_SUCCESS";
	String DELETEDANGER_FAILURE = "DELETEDANGER_FAILURE";
	
	String DANGERMONITOR = "DANGERMONITOR";
	String CHILDINDANGER = "CHILDINDANGER";
	String CHILDOUTOFDANGER = "CHILDOUTOFDANGER";
}
